(1) Updated dl_gitmodules to reduce reliance on subshell calls and instead use built-in bash functionality; (2) Added symlink to updated ack executable

diff --git a/bin/dl_gitmodules b/bin/dl_gitmodules
--- a/bin/dl_gitmodules
+++ b/bin/dl_gitmodules
@@ -1,23 +1,30 @@
 #!/bin/bash
 
 function is_git_repo () {
-    [[ -d "${PWD}"/.git ]] || git rev-parse --git-dir &>/dev/null
+    local moduledir="${1:-$PWD}"
+    [[ -d "${moduledir}/.git" ]] || git rev-parse --git-dir &>/dev/null
 }
 
-gitmodules_file="${PWD}"/.gitmodules
+moduledir="${1:-$PWD}"
+if ! pushd "$moduledir" &>/dev/null; then
+	echo "Can't chdir to ${moduledir}; exiting" 1>&2
+	exit 1
+fi
 
-if ! is_git_repo; then
+gitmodules_file="${moduledir}/.gitmodules"
+
+if ! is_git_repo "$moduledir"; then
     echo "${PWD} is not a git repository" 1>&2
     exit 2
 fi
 
-if ! [[ -f "${gitmodules_file}" ]]; then
-    echo "${gitmodules_file} does not exist" 2>&2
-    exit 2
+if ! [[ -f "$gitmodules_file" ]]; then
+    echo "${gitmodules_file} does not exist" 1>&2
+    exit 1
 fi
 
 while read path_key path; do
-    url_key="$(sed 's/\.path/.url/g' <<<"${path_key}")"
+    url_key="${path_key//\.path/.url}"
     url="$(git config -f "${gitmodules_file}" --get "${url_key}")"
-    git submodule add "${url}" "${path}"
+    git submodule add -f "${url}" "${path}"
 done < <(git config -f "${gitmodules_file}" --get-regexp '^submodule\..*\.path$')
