Added cpan module management to bin/dotfiles and also updated optional setup with irrsi

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -15,8 +15,9 @@ new_dotfiles_install="0"
 skip_init="0"
 noclobber="1"
 
-# Flags for whether to print link/copy operations
+# Flags for whether to print link/copy/etc. operations
 print_want_header="1"
+print_cpan_header="1"
 print_copy_header="1"
 print_skel_header="1"
 print_link_header="1"
@@ -24,6 +25,10 @@ print_link_header="1"
 # Flag for whether to print help doc
 print_help="0"
 
+# RC files to not clobber when linking
+declare -a noclobber_rcs=(bashrc bash_login bash_logout bash_profile muttrc subversion perlbrew ssh)
+
+# Set package manager stuff based on platform
 if [[ "$(cat /etc/issue 2> /dev/null)" =~ Arch ]]; then
     PKG_INSTALL="packer -S "
     PKG_CHECK_INSTALLED="pacman -Qqs "
@@ -40,111 +45,25 @@ else
     PKG_INSTALL=""
 fi
 
-# RC files to not clobber when linking
-declare -a noclobber_rcs=(bashrc bash_login bash_logout bash_profile muttrc subversion perlbrew ssh)
-
-while getopts ":nscqh" opt
-do
-  case $opt in
-    n)
-      new_dotfiles_install="1"
+# Get cpanm binary paths
+for bin in `whereis cpanm`; do
+  case $bin in
+    ${HOME}*cpanm)
+      CPANM_LOCAL=$bin
       ;;
-    s)
-      skip_init="1"
+    *cpanm)
+      CPANM_SYS="$bin --sudo"
       ;;
-    c)
-      noclobber="0"
-      ;;
-    q)
-      print_want_header="1"
-      print_copy_header="0"
-      print_skel_header="0"
-      print_link_header="0"
-      ;;
-    h)
-      print_help="0"
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
+    *)
       ;;
   esac
 done
-
-#exit
-
-[[ "$new_dotfiles_install" -eq "1" ]] && echo "This is a new installation"
-[[ "$skip_init" -eq "1" ]] && echo "Skipping initialization"
-[[ "$noclobber" -eq "1" ]] && echo "Preserving some existing configurations"
-
-# Set up global control flow variables.
-#if [[ "$2" ]]; then
-#  new_dotfiles_install="$2"
-#  [[ "$new_dotfiles_install" -eq "1" ]] && echo "This is a new installation"
-#else
-#  new_dotfiles_install="0"
-#fi
-#if [[ "$3" ]]; then
-#  skip_init="$3"
-#  [[ "$skip_init" -eq "1" ]] && echo "Skipping initialization"
-#else
-#  skip_init="0"
-#fi
 
 # Logging stuff.
 function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
 function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
 function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
 function e_arrow()    { echo -e " \033[1;33m➜\033[0m  $@"; }
-
-# Check whether a program exists
-function exists() {
-    command -v $1 >/dev/null 2>&1
-}
-
-export -f exists
-
-# Echoes a string representing a directory
-# specification minus the root directory.
-#
-# E.g., the relpath of 'foo/bar/baz'
-# is 'bar/baz'
-function relpath() {
-    local fullpath="$1"
-    OIFS="$IFS"
-    IFS="/"
-    dir_arr=($fullpath)
-    echo "${dir_arr[*]:1}"
-    IFS="$OIFS"
-}
-
-# Echoes a string representing a directory
-# specification minus the last directory/file.
-#
-# E.g., the pathname of 'foo/bar/baz'
-# is 'foo/bar'
-function pathname() {
-    local fullpath="$1"
-    OIFS="$IFS"
-    IFS="/"
-    dir_arr=($fullpath)
-    echo "${dir_arr[*]::(${#dir_arr[@]}-1)}"
-    IFS="$OIFS"
-}
-
-# Echoes a string representing the root
-# directory of a directory specification.
-#
-# E.g., the basedir of 'foo/bar/baz'
-# is 'foo'
-function basedir() {
-    local fullpath="$1"
-    OIFS="$IFS"
-    IFS="/"
-    dir_arr=($fullpath)
-    echo "${dir_arr[*]::1}"
-    IFS="$OIFS"
-}
 
 # Given a list of desired items and installed items, return a list
 # of uninstalled items. Arrays in bash are insane (not in a good way).
@@ -218,6 +137,41 @@ function want_do() {
     e_header "Installing $to_install"
     $PKG_INSTALL $to_install
   fi
+}
+
+# Copy files.
+function cpan_header() {
+  if [[ "$print_cpan_header" -eq "1" ]]; then
+    e_header "Installing CPAN modules";
+    print_cpan_header="0"
+  fi
+}
+
+function cpan_test() {
+    if ! exists cpanm; then
+      echo "cpanm CPAN module management utility not available"
+    fi
+}
+
+# Initialize.
+function cpan_do() {
+  local CPANM
+
+  # Install to system perl libs if the file we're processing is in the 'system' subdirectory
+  if [[ "$2" =~ system/[^/]+$ ]]; then
+    CPANM="$CPANM_SYS"
+  elif [[ "$2" =~ local/[^/]+$ ]]; then
+    CPANM="$CPANM_LOCAL"
+  else
+    return 1
+  fi
+
+  # Try to install package; if something breaks, ask for manual intervention
+  for pkg in `tr '\n' ' ' < $2`; do
+    if ! $CPANM $pkg; then
+      $CPANM --interactive $pkg
+    fi
+  done
 }
 
 # Copy files.
@@ -394,6 +348,7 @@ function do_stuff() {
     # Do stuff.
     local _do="_do"
     basedir_do="$basedir$_do"
+    # This will invoke, e.g., link_do "/home/user/.bashrc" "/home/user/.dotfiles/link/.bashrc"
     "$basedir_do" "$dest" "$file"
   done
 }
@@ -403,6 +358,14 @@ function do_stuff() {
 function process_opt_dirs() {
   local dir_type
   local opt_dirs=($DOTFILES_ROOT/opt/*)
+  local subdirs=(
+    init
+    want
+    cpan
+    copy
+    skel
+    link
+  )
 
   if (( ${#opt_dirs[@]} == 0 )); then return; fi
   e_header "Processing optional directories"
@@ -413,12 +376,16 @@ function process_opt_dirs() {
     read -N 1 -t 15 -p "Process $opt_dir_base? [y/N] " process_dir; echo
 
     if [[ "$process_dir" =~ [Yy] ]]; then
+      print_want_header="1"
+      print_cpan_header="1"
       print_copy_header="1"
+      print_skel_header="1"
       print_link_header="1"
-      local subdirs=($DOTFILES_ROOT/opt/$opt_dir_base/*)
 
-      for subdir in "${subdirs[@]}"; do
-          do_stuff "$(basename $subdir)" "opt/$opt_dir_base"
+      for subdir in ${subdirs[@]}; do
+          if [[ -d "$DOTFILES_ROOT/opt/$opt_dir_base/$subdir" ]]; then
+            do_stuff "$subdir" "opt/$opt_dir_base"
+          fi
       done
     fi
   done
@@ -450,9 +417,6 @@ function init_dotfiles() {
   [[ $print_help -eq 1 ]] && flags="${flags}h"
 
   e_header "Executing updated $SCRIPT_NAME script"
-  # Pass '1's as arguments so that we skip
-  # initialization on re-execution
-  #$SCRIPT 0 $new_dotfiles_install $skip_init
   $SCRIPT $flags
   unset flags
   exit 0
@@ -477,28 +441,59 @@ HELP
 
 # Enough with the functions, let's do stuff.
 
+# Grab command-line options
+while getopts ":nscqh" opt
+do
+  case $opt in
+    n)
+      new_dotfiles_install="1"
+      ;;
+    s)
+      skip_init="1"
+      ;;
+    c)
+      noclobber="0"
+      ;;
+    q)
+      print_want_header="1"
+      print_copy_header="0"
+      print_skel_header="0"
+      print_link_header="0"
+      ;;
+    h)
+      print_help="0"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+# Source some utilities & helpers.
+source $DOTFILES_ROOT/source/10_misc.sh
+
 # Initial stuff; do only if we haven't updated to the newest version
 if [[ "$skip_init" -ne "1" ]]; then
   intro $print_help
 
   e_header "Performing initial configuration"
   # Ensure that we can actually, like, compile anything.
-  if [[ ! "$(type -P gcc)" && "$OSTYPE" =~ ^darwin ]]; then
+  if ! exists gcc && [[ "$OSTYPE" =~ ^darwin ]]; then
     e_error "XCode or the Command Line Tools for XCode must be installed first."
     exit 1
   fi
-
+  e_header
   # If Git is not installed, install it (Ubuntu only, since Git comes standard
   # with recent XCode or CLT)
-  if [[ ! "$(type -P git)" && "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]]; then
+  if ! exists git ; then
     e_header "Installing Git"
-    sudo apt-get -qq install git-core
-  fi
-
-  # If Git isn't installed by now, something exploded. We gots to quit!
-  if [[ ! "$(type -P git)" ]]; then
-    e_error "Git should be installed. It isn't. Aborting."
-    exit 1
+    # The second or-clause is a cludge -- on Arch, packer won't be installed yet, so $PKG_INSTALL is
+    # not going to work.
+    if ! $PKG_INSTALL install git || sudo pacman -S git || $PKG_INSTALL git-core; then
+        e_error "Git should be installed. It isn't. Aborting."
+        exit 1
+    fi
   fi
 
   # Update existing sudo time stamp if set, otherwise do nothing.
@@ -507,10 +502,11 @@ if [[ "$skip_init" -ne "1" ]]; then
   # Initialize.
   e_header "Pulling in updated dotfiles repo"
   init_dotfiles
+else
+  e_header "Skipping initialization"
 fi
 
-# Utilities, helpers.
-source $DOTFILES_ROOT/source/10_misc.sh
+[[ "$noclobber" -eq "1" ]] && e_header "Preserving some existing configurations"
 
 # Add binaries into the path
 PATH=$DOTFILES_ROOT/bin:$PATH
@@ -530,6 +526,7 @@ backup=
 # Execute code for each file in these subdirectories.
 do_stuff "init"
 do_stuff "want"
+do_stuff "cpan"
 do_stuff "copy"
 do_stuff "skel"
 do_stuff "link"
@@ -542,6 +539,7 @@ fi
 
 # Lest I forget to do a few additional things...
 if [[ "$new_dotfiles_install" -eq "1" && -e "conf/firsttime_reminder.sh" ]]; then
+  e_header "This is a new installation"
   e_header "First-Time Reminders"
   source "conf/firsttime_reminder.sh"
 fi
