Revised usage

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -57,7 +57,7 @@ else
     e_prompt ()   { printf "\n \037[1;35m?\033[0m %b " "$@"; }
     e_success ()  { printf " \033[1;32m:)\033[0m %b\n" "$@"; }
     e_error ()    { printf " \033[1;31m:(\033[0m %b\n" "$@"; }
-    e_fatal ()    { printf " \033[1;31m:S\033[0m %b\n" "$@"; }
+    e_fatal ()    { printf " \033[1;31m:/\033[0m %b\n" "$@"; }
     e_arrow ()    { printf " \033[1;33m->\033[0m %b\n" "$@"; }
 fi
 
@@ -198,21 +198,26 @@ process () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     local optype_file="$1"
-    local optype
+    shift
 
     # Unset these functions in case the sourced file doesn't define them.
     # Otherwise, some previously-defined function could run.
-    unset
-    unset -f check run
+    unset processdir header
+    unset -f check run parseopts
 
     if [[ -f "$optype_file" ]]; then
-        source "$optype_file"
+        source "$optype_file" &>/dev/null
     else
         e_error "No such file: $optype_file" 1>&2
         return 1
     fi
 
-    local srcdir
+    # Silently ignore any operation types that haven't been declared.
+    if ! declare -F run &>/dev/null; then
+        return 0
+    fi
+
+    local optype
     if [[ -n "${processdir:-}" ]]; then
         optype="${processdir##*/}"
     else
@@ -229,15 +234,11 @@ process () {
 
     # If processdir contains a leading slash, treat it as an absolute path.
     # Otherwise, assume we're looking for a relative path in DOTFILES_ROOT.
+    local srcdir
     if [[ "${processdir:-}" =~ ^/ ]]; then
         srcdir="$processdir"
     else
         srcdir="${DOTFILES_ROOT}/${optype}"
-    fi
-
-    # Silently ignore any operation types that haven't been declared.
-    if ! declare -F run &>/dev/null; then
-        return 0
     fi
 
     # Print a pretty header :)
@@ -248,6 +249,8 @@ process () {
         e_error "No such directory: $srcdir" 1>&2
         return 1
     fi
+
+    parseopts "$@"
 
     # Iterate over files.
     local skip_reason srcfile srcstem destfile backup_subpath
@@ -282,7 +285,7 @@ process () {
         run "$srcfile" "$destfile"
     done < <(find_hierarchical "$srcdir" --prefix "$DOTFILES_ROOT" -xtype f)
 
-    [[ $failed -eq 0 ]]
+    (( failed == 0 ))
 }
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@@ -290,9 +293,12 @@ process_all () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     local rundir="$1"
-    local run_extension="${2:-.sh}"
+    shift
+
+    local run_extension=".sh"
+
     for optype_file in "${rundir}/"*"${run_extension}"; do
-        process "$optype_file"
+        process "$optype_file" "$@"
     done
 }
 
@@ -372,7 +378,9 @@ usage () {
 
     if (( $return_code != 0 )); then
         printf '%s' "
-Usage: $SCRIPT_BASENAME [-n] [-s] [-c] [-h] [-P FILES] [-B PATH] [-R PATH] [-C PATH] [-v] [-V] [-q] [-h]
+Usage: $SCRIPT_BASENAME [OPTIONS] [-- [PASSTHRU OPTIONS]]
+
+Please run 'dotfiles --help' for detailed usage.
 "
 
         return "$return_code"
@@ -403,8 +411,9 @@ Usage: $SCRIPT_BASENAME [-n] [-s] [-c] [-h] [-P FILES] [-B PATH] [-R PATH] [-C P
                         (currently: ${DOTFILES_CACHE_PATH}).
 
 -R, --rundir PATH       The directory in which dotfiles will search for its
-                        marching orders (currently: ${DOTFILES_RUNDIR}).  See
-                        README.md for details.
+                        marching orders (currently: ${DOTFILES_RUNDIR}).  If
+                        the path is relative, it's assumed to be relative to
+                        DOTFILES_ROOT. See README.md for details.
 
 -v, --verbose           Tell dotfiles to be chatty.
 
@@ -414,6 +423,9 @@ Usage: $SCRIPT_BASENAME [-n] [-s] [-c] [-h] [-P FILES] [-B PATH] [-R PATH] [-C P
 -q, --quiet             Tell dotfiles to pipe it down, guldarnit!
 
 -h, --help              Print this message.
+
+If $SCRIPT_BASENAME sees a bare '--', it assumes that options processing is
+done and passes any further parameters to the scripts in ${DOTFILES_RUNDIR}.
 "
 
     return "$return_code"
@@ -501,8 +513,12 @@ main () {
 
     local opt_name opt_value
     while (( $# )); do
-        read opt_name opt_value <<<"$@"
+        read opt_name opt_value _ <<<"$@"
         case "$opt_name" in
+            --)
+                shift
+                break
+                ;;
             -n|--new-install)
                 DOTFILES_NEW_INSTALL=true
                 shift
@@ -520,7 +536,12 @@ main () {
                 shift 2
                 ;;
             -R|--rundir)
-                DOTFILES_RUNDIR="$opt_value"
+                if [[ "$opt_value" =~ ^/ ]]; then
+                    DOTFILES_RUNDIR="$opt_value"
+                else
+                    DOTFILES_RUNDIR="${DOTFILES_ROOT}/$opt_value"
+                fi
+
                 shift 2
                 ;;
             -B|--backup-path)
@@ -533,10 +554,6 @@ main () {
                 ;;
             -v|--verbose)
                 DOTFILES_VERBOSE=true
-                shift
-                ;;
-            -V|--skip-vim-plugins)
-                DOTFILES_SKIP_VIM_PLUGINS=true
                 shift
                 ;;
             -q|--quiet)
@@ -608,7 +625,7 @@ main () {
 
     # Execute code for each file in these subdirectories.
     if [[ -d "$DOTFILES_RUNDIR" ]]; then
-        process_all "$DOTFILES_RUNDIR"
+        process_all "$DOTFILES_RUNDIR" "$@"
     else
         e_fatal "No such directory: ${DOTFILES_RUNDIR}" \
             "${SCRIPT_BASENAME} cannot proceed." 1>&2
@@ -617,7 +634,7 @@ main () {
 
     # Alert if backups were made.
     if (( "$__DOTFILES_BACKUP" > 0 )); then
-        e_arrow "\nBackups were moved to ${DOTFILES_BACKUP_PATH}\n"
+        e_arrow "Backups were moved to ${DOTFILES_BACKUP_PATH}"
     fi
 
     # Lest I forget to do a few additional things...
