big fixes/imporvements in

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -15,88 +15,67 @@ init_vars () {
     shopt -s dotglob
     shopt -s nullglob
 
-    SCRIPT_PATH="${BASH_SOURCE[0]}"
-    SCRIPT_BASENAME="${SCRIPT_PATH##*/}"
-    SCRIPT_DIRNAME="${SCRIPT_PATH%/*}"
+    declare -gr SCRIPT_PATH="${BASH_SOURCE[0]}"
+    declare -gr SCRIPT_BASENAME="${SCRIPT_PATH##*/}"
+    declare -gr SCRIPT_DIRNAME="${SCRIPT_PATH%/*}"
 
     # Globals
-    : "${DOTFILES_DESTDIR:=$HOME}"
-    : "${DOTFILES_ROOT:=$(readlink -e "${SCRIPT_DIRNAME}/../.dotfiles")}"
-    : "${DOTFILES_REPO:=git://github.com/BaxterStockman/dotfiles.git}"
-    : "${DOTFILES_NEW_INSTALL:=false}"
-    : "${DOTFILES_SKIP_INIT:=false}"
-    : "${DOTFILES_NOCLOBBER:=true}"
-    : "${DOTFILES_VERBOSE:=true}"
-    : "${DOTFILES_CACHE_PATH:=${DOTFILES_ROOT}/caches}"
-    : "${DOTFILES_BACKUP_PATH:=${DOTFILES_ROOT}/backup/$(date "+%Y_%m_%d-%H_%M_%S")}"
+    declare -gx DOTFILES_BACKUP_PATH="${DOTFILES_BACKUP_PATH:=${DOTFILES_ROOT}/backup/$(date "+%Y_%m_%d-%H_%M_%S")}"
+    declare -gx DOTFILES_CACHE_PATH="${DOTFILES_CACHE_PATH:=${DOTFILES_ROOT}/caches}"
+    declare -gx DOTFILES_DESTDIR="${DOTFILES_DESTDIR:=$HOME}"
+    declare -gx DOTFILES_NEW_INSTALL="${DOTFILES_NEW_INSTALL:=false}"
+    declare -gx DOTFILES_REPO="${DOTFILES_REPO:=git://github.com/BaxterStockman/dotfiles.git}"
+    declare -gx DOTFILES_ROOT="${DOTFILES_ROOT:=$(readlink -e "${SCRIPT_DIRNAME}/../.dotfiles")}"
+    declare -gx DOTFILES_SKIP_INIT="${DOTFILES_SKIP_INIT:=false}"
+    declare -gx DOTFILES_NOCLOBBER="${DOTFILES_NOCLOBBER:=true}"
+    declare -gx DOTFILES_VERBOSE="${DOTFILES_VERBOSE:=true}"
+    declare -gx DOTFILES_NOCLOBBER_EXT="${DOTFILES_NOCLOBBER_EXT:-.custom}"
+    declare -gx DOTFILES_NOCLOBBER_RCS="${DOTFILES_NOCLOBBER_RCS:-}"
+
     declare -gi __DOTFILES_BACKUP=0
     declare -gi __DOTFILES_FAILED=0
 
     # RC files to not clobber when linking
-    declare -ga DOTFILES_NOCLOBBER_RCS=(
-        bashrc
-        bash_login
-        bash_logout
-        bash_profile
-        muttrc
-        subversion
-        perlbrew
-        ssh
-    )
+    declare -gA __DOTFILES_NOCLOBBER_RC_MAP
+    if [[ -n "$DOTFILES_NOCLOBBER_RCS" ]]; then
+        local IFS=$','
+        local rc
+        for rc in $DOTFILES_NOCLOBBER_RCS; do
+            __DOTFILES_NOCLOBBER_RC_MAP["$rc"]=true
+        done
+        unset IFS
+    else
+        __DOTFILES_NOCLOBBER_RC_MAP=(
+            ['.bashrc']=true
+            ['.bash_login']=true
+            ['.bash_logout']=true
+            ['.bash_profile']=true
+            ['.muttrc']=true
+            ['.subversion']=true
+            ['.perlbrew']=true
+            ['.ssh']=true
+        )
+        local IFS=$','
+        export DOTFILES_NOCLOBBER_RCS="${!__DOTFILES_NOCLOBBER_RC_MAP[*]}"
+        unset IFS
+    fi
 }
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # Logging stuff
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-e_header ()   { echo -e "\n\033[1m$*\033[0m"; }
-e_success ()  { echo -e " \033[1;32m✔\033[0m  $*"; }
-e_error ()    { echo -e " \033[1;31m✖\033[0m  $*" 1>&2; }
-e_arrow ()    { echo -e " \033[1;33m➜\033[0m  $*"; }
+if [[ "$(locale charmap)" =~ UTF-8 ]]; then
+    e_header ()   { printf "\n\033[1;35m★★★★★★\033[0m %b \033[1;35m★★★★★★\033[0m\n\n" "$@"; }
+    e_success ()  { printf " \033[1;32m✔\033[0m  %b\n" "$@"; }
+    e_error ()    { printf " \033[1;31m✖\033[0m  %b\n" "$@"; }
+    e_arrow ()    { printf " \033[1;33m➜\033[0m  %b\n" "$@"; }
+else
+    e_header ()   { printf "\n\033[1;35m=====\033[0m %b \033[1;35m=====\033[0m\n\n" "$@"; }
+    e_success ()  { printf " \033[1;32m:)\033[0m  %b\n" "$@"; }
+    e_error ()    { printf " \033[1;31m:(\033[0m  %b\n" "$@"; }
+    e_arrow ()    { printf " \033[1;33m->\033[0m  %b\n" "$@"; }
+fi
 
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-__make_pretty () {
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    # Reset IFS, i.e. ensure that it's ' '
-    local IFS
-    # Split on whitespace
-    local -a maybe_util=($1)
-    # Extract the first element
-    local util="${maybe_util[0]}"
-
-    if [[ -z $util  ]]; then
-        echo "Please provide an executable name or path to wrap" 1>&2
-        return 1
-    fi
-
-    cat <<META
-${util}_pretty () {
-    local ${util}_output="\$(${util} "\$@")";
-    local -i exit_code=\$?;
-    local line
-
-    if [[ \$exit_code == 0 ]]; then
-        while read -r ${util}_output_line; do
-            e_arrow "\$${util}_output_line";
-        done <<<\$${util}_output;
-        return 0;
-    else
-        while read -r ${util}_output_line; do
-            e_error "\$${util}_output_line";
-        done <<<\$${util}_output;
-        return 1;
-    fi;
-};
-META
-}
-
-eval "$(__make_pretty 'mkdir')"
-eval "$(__make_pretty 'cp')"
-eval "$(__make_pretty 'ln')"
-
-declare -f mkdir_pretty
-declare -f ln_pretty
-
-unset -f __make_pretty
 
 # Given a list of desired items and installed items, return a list
 # of uninstalled items. Arrays in bash are insane (not in a good way).
@@ -165,7 +144,10 @@ copy_test () {
 #   - The destination file is newer than the source file.
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     local srcfile="$1"
-    local destfile="$1"
+    local maybe_destfile="$1"
+    local destfile
+
+    destfile="$(check_noclobber "$maybe_destfile")"
 
     if [[ -e "${destfile}" && ! "$(cmp "${srcfile}" "${destfile}" 2> /dev/null)" ]]; then
         echo "same file"
@@ -187,7 +169,7 @@ copy_do () {
     local destfile="$2"
     local destdir="${destfile%/*}"
 
-    if ! mkdir_pretty -p "$destdir"; then
+    if ! mkdir -p "$destdir" >/dev/null; then
         e_error "Can't copy ${srcfile} to ${destfile}"
         return 1
     fi
@@ -241,6 +223,7 @@ link_test () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     local srcfile="$1"
     local destfile="$2"
+
     if [[ "${srcfile}" -ef "${destfile}" ]]; then
         echo "${destfile} already links to ${srcfile}"
         return 0
@@ -250,33 +233,34 @@ link_test () {
 }
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-check_exists () {
+check_noclobber () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    if "${DOTFILES_NOCLOBBER}"; then
-        local dest_dir="$(pathname "$1")"
-        local srcfile=${2#$HOME/}
-        local destfile=$1
+    local srcfile="$1"
+    local destfile="$1"
+    local real_destfile="$destfile"
 
-        for rcname in "${DOTFILES_NOCLOBBER_RCS[@]}"; do
-            local rc="$dest_dir/.$rcname"
-            if [[ ${1#$dest_dir/} =~ \.$rcname ]] && [[ $(md5cmp "$src_file" "$rc") -eq 0 ]]; then
-                return 0
-            fi
-        done
+    if "${DOTFILES_NOCLOBBER}"; then
+        if [[ "${__DOTFILES_NOCLOBBER_RC_MAP["${destfile#$DOTFILES_DESTDIR}"]:-false}" == 'true' ]]; then
+            e_arrow "Not clobbering ${destfile};" \
+                "${srcfile} will be appended with '${DOTFILES_NOCLOBBER_EXT}'" 1>&2
+            real_destfile="${destfile}${DOTFILES_NOCLOBBER_EXT}"
+        fi
     fi
 
-    return 1
+    echo "$real_destfile"
 }
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 link_do () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     local srcfile="$1"
-    local destfile=$2
+    local maybe_destfile="$2"
+    local destfile
 
+    destfile="$(check_noclobber "$maybe_destfile")"
     local destdir="${destfile%/*}"
 
-    if ! mkdir_pretty -p "$destdir"; then
+    if ! mkdir -p "$destdir" >/dev/null; then
         e_error "Can't link ${destfile} to ${srcfile}"
         return 1
     fi
@@ -286,7 +270,7 @@ link_do () {
         e_arrow "Not clobbering ${dest_file}; ${src_file} will be appended with '.custom'"
     fi
 
-    ln_pretty -sf "$srcfile" "$destfile"
+    ln -sf "$srcfile" "$destfile"
     e_success "Linking ${srcfile} to ${destfile}"
 }
 
@@ -318,19 +302,24 @@ do_stuff () {
     srcdir_relpath="$1"
     optype="${srcdir_relpath##*/}"
     if [[ -z "$optype" ]]; then
-        echo "No optype specified" 1>&2
+        e_error "No optype specified" 1>&2
         return 1
+    fi
+
+    local optype_do="${optype}_do"
+    # Silently ignore any operation types that haven't been declared.
+    if ! declare -F "$optype_do" &>/dev/null; then
+        return 0
     fi
 
     srcdir="${DOTFILES_ROOT}/${srcdir_relpath}"
     if ! [[ -d "$srcdir" ]]; then
-        e_error "No such directory: $srcdir"
+        e_error "No such directory: $srcdir" 1>&2
         return 1
     fi
 
     # Run _header function only if declared.
     local optype_header="${optype}_header"
-    local optype_do="${optype}_do"
     declare -F "$optype_header" &>/dev/null && "$optype_header"
 
     # Run _test function only if declared.
@@ -348,7 +337,7 @@ do_stuff () {
             # message.
             skip_reason="$("$test_func" "$srcfile" "$destfile")"
             if [[ -n "$skip_reason" ]]; then
-                e_error "Skipping ${optype}/${srcstem}: ${skip_reason}."
+                e_error "Skipping ${optype}/${srcstem}: ${skip_reason}" 1>&2
                 continue
             fi
 
@@ -363,7 +352,7 @@ do_stuff () {
                 if ! [[ -e "$backup_subpath" ]]; then
                     mkdir -p "$backup_subpath"
                 elif ! [[ -d "$backup_subpath" ]]; then
-                    e_error "${backup_subpath} exists but is not a directory"
+                    e_error "${backup_subpath} exists but is not a directory" 1>&2
                     ((failed++))
                 fi
 
@@ -402,7 +391,7 @@ do_opt_stuff () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 init_dotfiles() {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    $DOTFILES_SKIP_INIT && return 0
+    [[ $DOTFILES_SKIP_INIT == 'true' ]] && return 0
 
     # Skip this function after we exec the updated version of this script.
     export DOTFILES_SKIP_INIT=true
@@ -419,6 +408,7 @@ init_dotfiles() {
         pushd "$DOTFILES_ROOT" >/dev/null
         git pull
         git submodule update --init --recursive --quiet || :
+        popd >/dev/null
     fi
 
     e_header "Executing updated ${SCRIPT_BASENAME} script"
@@ -443,55 +433,73 @@ EOF
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 main () {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    init_vars
-
+    local opt_name opt_value
     # Grab command-line options
     while (( $# )); do
         read opt_name opt_value <<<"$@"
-        case "${opt_name/-?(-)/}"/ in
-            n|new-install)
+        case "$opt_name" in
+            -n|--new-install)
                 DOTFILES_NEW_INSTALL=true
+                shift
                 ;;
-            s|skip-init)
+            -s|--skip-init)
                 DOTFILES_SKIP_INIT=true
+                shift
                 ;;
-            c|clobber)
+            -c|--clobber)
                 DOTFILES_NOCLOBBER=false
+                shift
                 ;;
-            v|verbose)
+            -P|--preserve)
+                DOTFILES_NOCLOBBER_RCS="$opt_value"
+                shift 2
+                ;;
+            -B|--backup-path)
+                DOTFILES_BACKUP_PATH="$opt_value"
+                shift 2
+                ;;
+            -C|--cache-path)
+                DOTFILES_CACHE_PATH="$opt_value"
+                shift 2
+                ;;
+            -v|--verbose)
                 DOTFILES_VERBOSE=true
+                shift
                 ;;
-            q|quiet)
+            -q|--quiet)
                 DOTFILES_VERBOSE=false
+                shift
                 ;;
-            h|help)
-                print_help=false
+            -h|--help)
+                usage
+                exit 0
                 ;;
-            \?)
+            *)
                 echo "Invalid option: ${opt_name}" 1>&2
                 exit 1
                 ;;
         esac
     done
 
+    # NOW initialize variable.
+    init_vars
+
     # Initial stuff; do only if we haven't updated to the newest version
-    if ! "$DOTFILES_SKIP_INIT"; then
+    if ! [[ "$DOTFILES_SKIP_INIT" == 'true' ]]; then
         usage
 
         e_header "Performing initial configuration"
 
         # Ensure that we can actually, like, compile anything.
         if ! command -v gcc >/dev/null 2>&1 && [[ "$OSTYPE" =~ ^darwin ]]; then
-            e_error "XCode or the Command Line Tools for XCode must be installed first."
+            e_error "XCode or the Command Line Tools for XCode must be installed first." 1>&2
             exit 1
         fi
-
-        e_header
 
         # If Git is not installed, install it (Ubuntu only, since Git comes
         # standard with recent XCode or CLT)
         if ! type -a git >/dev/null 2>&1; then
-            e_error "Git should be installed. It isn't. Aborting."
+            e_error "Git should be installed. It isn't. Aborting." 1>&2
             exit 1
         fi
 
@@ -520,7 +528,10 @@ main () {
     mkdir -p "$DOTFILES_CACHE_PATH"
 
     # Execute code for each file in these subdirectories.
-    for optype in init copy skel link; do
+    local dotfiles_subdir
+    for dotfiles_subdir in "$DOTFILES_ROOT"/*; do
+        optype="${dotfiles_subdir##*/}"
+        declare -F "${optype}_do" &>/dev/null || continue
         do_stuff "$optype"
         do_opt_stuff "$optype"
     done
@@ -542,6 +553,8 @@ main () {
     return 0
 }
 
-# Enough with the functions, let's do stuff.
-main "$@"
-exit $?
+if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
+    # Enough with the functions, let's do stuff.
+    main "$@"
+    exit $?
+fi
